import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#393939] text-white ${inter.className}`}>
        <header className='container mx-auto pt-5 flex justify-between items-center'>
          <h1 className='text-4xl md:text-5xl font-bold'>Logo</h1>
          <nav className='flex gap-5 justify-end text-lg md:text-xl'>
            <a className='hover:text-white duration-300' href="/">Home</a>
            <a className='hover:text-white duration-300' href="/newVehicle">New vehicle</a>
          </nav>
        </header>
        
        {children}
      </body>
    </html>
  )
}
