import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`relative bg-white text-primary ${inter.className}`}>
        <div className="absolute h-screen w-[30%] top-0 right-0 -z-10">
          <Image
            src={'/Triangulinhux.svg'}
            alt='triangles'
            fill
            className='object-center'
          />
        </div>

        <header className='container mx-auto pt-5 flex justify-center items-center'>
          <a href='/' className='text-4xl md:text-5xl font-bold z-10'>Logo</a>
        </header>
        
        {children}
      </body>
    </html>
  )
}
